username:  # <- Your Username Account
password:  # <- Tour Password Account

debug: false # <- debug mode

sync_mobile: false # <- If your are uID and accessToken and your phone bot use configuration for login please replace your uid and accesstoken sync to phone. (Recommended OFF)

# exemple ['All', '!showMsgTotalBruteForceInfo'] <- show all but don't show Total Brute Force Information return bot print.
# exemple ['showMsgTotalBruteForceInfo'] <- just show Total Brute Force Information return bot print.
show_info: [All] # <- show the return bot print information

# attack mode it's method for attack the bot, attack in bank ip save, ip List, or attack new ip 
# - new -> -> if scan new user for attack
# - bank_scan -> if scan user in bank
# - ip_list -> if user exist in target bruteforce recollect money
attack_mode: bank_scan

uID:  # <- Automatically added uID for your account don't change /!\
accessToken:  # <- Automatically added accessToken for your account don't change /!\
update: [SDK, FW, AV, BP, IPSP] # All Apps: AV, FW, SPAM, BRUTE, BP, SDK, IPSP
msgLog: "Hacked with <3 by #PB"  # <- It is recommented to change this message /!\

# Socks 5 Proxy
socks_enable: false # <- if true it will use the config below
socks_https: true # <- this should only be true when the proxy supports HTTPS/SSL/TLS
socks_host: localhost # <- the server's ip address or domain name
socks_port: 1080 # <- the port the proxy is running on
socks_login: false # <- this should only be true when the proxy needs a username and password
socks_user: # <- the username for the proxy (DO NOT USE SPECIAL CHARACTERS HERE)
socks_pass: # <- the password for the proxy user (DO NOT USE SPECIAL CHARACTERS HERE)
